export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR';

export const REQUEST_ADS = 'REQUEST_ADS';
export const RECEIVE_ADS = 'RECEIVE_ADS';
export const REQUEST_ADS_ERROR = 'REQUEST_ADS_ERROR';

export const REQUEST_PDT_DETAIL = 'REQUEST_PDT_DETAIL';
export const RECEIVE_PDT_DETAIL = 'RECEIVE_PDT_DETAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
